-- DELETE TRIGGER
DROP FUNCTION f_setDeleteForPage() CASCADE;

-- DELETE TABLE
DROP TABLE IF EXISTS "DeletePage";
DROP TABLE IF EXISTS "Rate";
DROP TABLE IF EXISTS "Frame";
DROP TABLE IF EXISTS "Page";
DROP TABLE IF EXISTS "User";
